# Generated by Django 5.1 on 2024-09-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=255)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("cone", "Cone"),
                            ("sundae", "Sundae"),
                            ("cake", "Cake"),
                        ],
                        default="bar",
                        max_length=10,
                    ),
                ),
                ("list", models.BooleanField(default=False)),
            ],
        ),
    ]
